services:
  mysql:
    container_name: 'mysql'
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./docker-volumes/mysql_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./docker-volumes/redis_data:/data

  location-service:
    build: .
    container_name: location-service
    ports:
      - '80:80'
    env_file:
      - .env.production
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
