services:
  mysql:
    container_name: 'mysql'
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./docker-volumes/mysql_data:/var/lib/mysql

volumes:
  mysql_data:
